shallow_clone: true
version: '{branch}-{build}'
cache:
  - C:\projects\qutebrowser\.cache
build: off
os: Previous Windows Server 2012 R2
environment:
    PYTHON: 'C:\Python34'
    PYTHONUNBUFFERED: 1

install:
  - C:\Python27\python -u scripts\dev\ci_install.py

test_script:
  - C:\Python34\Scripts\tox -e py34
  - C:\Python34\Scripts\tox -e unittests-frozen
  - C:\Python34\Scripts\tox -e smoke-frozen
  - C:\Python34\Scripts\tox -e pyflakes
  - C:\Python34\Scripts\tox -e pylint
