dist: trusty

# Not really, but this is here so we can do stuff by hand.
language: c

install:
  - sudo apt-get -y -q update
  - sudo apt-get -y -q install python3-pyqt5 python3-pyqt5.qtwebkit python-tox python3-dev xvfb

script:
    - xvfb-run -s "-screen 0 640x480x16" tox -e unittests,smoke
    - tox -e misc
    - tox -e pep257
    - tox -e pyflakes
    - tox -e pep8
    - tox -e mccabe
    - tox -e pylint
    - tox -e pyroma
    - tox -e check-manifest
